Created model of Book and repository with service for it using Spring…
Vlad1507/spring-boot-book-store pull request #1
Opened 2024-09-30 16:10 UTC by Vlad1507

… Boot.

2024-10-01 08:01 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/models/Book.java
> +    private String isbn;
Let's add appropriate requirements to the fields, for example for isbn
 ```
@Column(nullable = false, unique = true) 
 private String isbn;
```

2024-10-01 08:02 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +    @Autowired
```suggestion
```
This annotation is optional

2024-10-01 08:03 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't save book: " + book + " in the database");
```suggestion
            throw new DataProcessingException("Can't save book: " + book + " in the database");
```

2024-10-01 08:03 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books from database");
the same

2024-10-01 08:03 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/services/impl/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-10-03 08:36 UTC, okuzan requested changes
git rm --cached .idea, same for target
they definitely shouldn't be in git
mvnw files are optional

2024-10-03 14:11 UTC, Elena-Bruyako requested changes
see comments

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/BookStoreApplication.java
> +            Book whiteFang = new Book();
```suggestion
            Book book = new Book();
```

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/exception/DataProcessingException.java
> +
```suggestion
```

remove empty line after class declaration

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/models/Book.java
> +@Data
```suggestion
@Getter
@Setter
@Table(name...)
```

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/services/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-10-03 14:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/services/impl/BookServiceImpl.java
> +    }
```suggestion
```

2024-10-03 18:38 UTC, Elena-Bruyako approved these changes

2024-10-28 12:58 UTC, Elena-Bruyako requested changes
see comments
Please, fix previous comments

2024-10-28 12:58 UTC, Elena-Bruyako commented on .github/workflows/ci.yml
> +name: Java CI
add .idea to gitignore

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/BookStoreApplication.java
> +    private BookService bookService;
remove unused service

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/dto/BookDto.java
> +
remove empty line

```suggestion
```

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/exception/DataProcessingException.java
> +
comment not fixed

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/exception/EntityNotFoundException.java
> +
remove empty line
```suggestion
```

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/mapper/BookMapper.java
> +
remove empty line

```suggestion
```

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/models/Book.java
> +@Data
comment not fixed

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/repository/impl/BookRepositoryImpl.java
> +        }
add catch block

2024-10-28 12:58 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/services/impl/BookServiceImpl.java
> +        return bookRepository.findById(id)
stream works slowly so there is no purpose to use it
```suggestion
        Book book = bookRepository.findById(id).orElseThrow(
                        () -> new EntityNotFoundException("Can't get a book by id: " + id)
                );
        return bookMapper.toDto(book);
```

2024-10-29 07:57 UTC, liliia-ponomarenko requested changes
Good job! But let’s fix my comment and issue with gitignore!

2024-10-29 07:57 UTC, liliia-ponomarenko commented on pom.xml
> +	</repositories>
Why do you need it? And you duplicate it.

2024-10-29 07:57 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/dto/CreateBookRequestDto.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Let’s  remove this annotation
```suggestion
```

2024-10-29 14:39 UTC, Elena-Bruyako requested changes
one comment

2024-10-29 14:39 UTC, Elena-Bruyako commented on .github/workflows/ci.yml
> +name: Java CI
I didin't find .gitignore file in your project, please add it

2024-10-30 09:59 UTC, okuzan approved these changes

2024-11-21 10:19 UTC, merged