Jv spring boot book store 3
Vlad1507/spring-boot-book-store pull request #3
Opened 2024-11-20 21:10 UTC by Vlad1507

2024-11-21 09:35 UTC, okuzan requested changes
Why so many unrelated changes? Have you merged previously approved PRs into Main?

2024-11-21 18:11 UTC, Elena-Bruyako requested changes
see comments

There are a lot of changes from previous HW, you should provide implementation of particular HW only

2024-11-21 18:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/models/Book.java
> +    private String author;
```suggestion
    @Column(nullable = false)
    private String title;
    @Column(nullable = false)
    private String author;
```

2024-11-21 18:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/models/Book.java
> +    @Column(nullable = false, unique = true, name = "isbn")
```suggestion
    @Column(nullable = false, unique = true)
```

2024-11-21 18:11 UTC, Elena-Bruyako commented on src/main/java/com/store/bookstore/services/impl/BookServiceImpl.java
> +        book.setId(id);
```suggestion
        bookMapper.updateBookFromDto(bookRequestDto, book);
```

2024-11-23 11:45 UTC, Elena-Bruyako approved these changes

2024-12-11 22:47 UTC, merged