Jv spring boot book store 4
Vlad1507/spring-boot-book-store pull request #4
Opened 2024-12-04 19:34 UTC by Vlad1507

2024-12-05 07:47 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-12-05 07:47 UTC, liliia-ponomarenko commented on pom.xml
> +		</dependency>
better use spring starter validation

2024-12-05 07:47 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/mapper/BookMapper.java
> +    @Modifying
why do you need this annotation?

2024-12-05 07:47 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/validation/IsbnValidator.java
> +        String formattedIsbn = matcher.replaceFirst("$1-$2-$3-$4-$5");
Why do you need it? Can it provide some exceptions?

2024-12-05 07:47 UTC, liliia-ponomarenko commented on src/main/java/com/store/bookstore/exception/CustomGlobalExceptionHandler.java
> +public class CustomGlobalExceptionHandler extends ResponseEntityExceptionHandler {
Let’s  handle EntityNotFoundException and return 404 status code

2024-12-10 12:18 UTC, Elena-Bruyako approved these changes
One comment about version, you can fix it in the next task

2024-12-10 12:18 UTC, Elena-Bruyako commented on pom.xml
> +			<version>3.4.0</version>
```suggestion
```

2024-12-11 22:47 UTC, merged